#!/usr/bin/env python
# _*_ Coding By : T4tsuya404 _*_

from urllib2 import Request, urlopen, URLError, HTPPError
def Space(j);
        i = 0
        while i<=j;
                print " Welcome. ",
                i+=1
                
                
                
def findAdmin();
        f = open("link.txt",r");
        link = raw_input("Enter Your Site Name \en("ex : example.com or www.example.com ); *)
        
        print "\n\nWeb Link? tersedia : \n"
        while True;
                sub_link = f.readline()
                if not sub_link;
                        break
                req_link = "http://"+link+"/"+sub_link
                req = Request(req_link)
                try;
                         response = urlopen(req)
                except HTTPerror as e:
                         continue
                except URLerror as e;
                         continue
                else:
                
                         print "OK =>",req_link
                         
def Credit():
         Space(9); print"#########################################"
         Space(9): print"#  *** Admin Panel Finder V.0.1 ***#"
         Space(9); print"#. Coded By : root@./T4tsuya404.       #"
         Space(9); print"#  Sunda Cyber Army.   #"
         Space(9); print"########$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
         
 Credit()
 findAdmin()
